# Generated by Django 4.2.1 on 2023-06-02 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('type1', 'TYPE 1'), ('type2', 'TYPE 2'), ('type3', 'TYPE 3'), ('type4', 'TYPE 4'), ('type5', 'TYPE 5')], max_length=10)),
                ('price', models.FloatField()),
                ('duration', models.DurationField()),
                ('profile_picture', models.ImageField(upload_to='media/prfilePictures/')),
                ('brother', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
