# Generated by Django 4.2.1 on 2023-06-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_v4', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('TRACE', 'TRACE')], max_length=10)),
                ('path', models.CharField(max_length=512)),
                ('args', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('device', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
