# Generated by Django 4.2.1 on 2023-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='smtp_url',
            new_name='smtp',
        ),
        migrations.AddField(
            model_name='email',
            name='imap',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='star',
            field=models.BooleanField(default=False),
        ),
    ]
