# Generated by Django 4.2.1 on 2023-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_smtp_url_email_smtp_email_imap_email_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='port',
            new_name='port_smtp',
        ),
        migrations.AddField(
            model_name='email',
            name='port_imap',
            field=models.IntegerField(default=587),
        ),
    ]
