# Generated by Django 4.2.1 on 2023-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_log_session_log_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='protocol',
        ),
        migrations.AlterField(
            model_name='log',
            name='device',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
