# Generated by Django 4.2.1 on 2023-12-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_account_gender_alter_account_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='manyToManyRel',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='oneToOneRel',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
