# Generated by Django 4.2.1 on 2023-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_log_protocol_alter_log_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/testmodel/')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
            ],
        ),
    ]
