# Generated by Django 4.2.1 on 2023-07-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.JSONField()),
            ],
        ),
    ]
