# Generated by Django 4.2.1 on 2023-07-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboardconfiguration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DashboardConfiguration',
            new_name='Configuration',
        ),
    ]
