# Generated by Django 4.2.1 on 2023-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_dashboardconfiguration_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_some', models.BooleanField(null=True)),
                ('other', models.FileField(upload_to='To_REMOVE_Media/images')),
            ],
        ),
    ]
