# Generated by Django 4.2.1 on 2023-07-24 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='Media/dashboard/account/')),
                ('bio', models.TextField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=24, null=True)),
                ('address', models.CharField(max_length=32, null=True)),
                ('street', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
                ('state', models.CharField(max_length=32, null=True)),
                ('zip_code', models.CharField(max_length=6, null=True)),
                ('website', models.CharField(max_length=64, null=True)),
                ('pronouns', models.CharField(max_length=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
