# Generated by Django 4.2.1 on 2023-08-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_log_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField()),
                ('file', models.ImageField(upload_to='Media/dashboard/auth/qrcode')),
            ],
        ),
    ]
