# Generated by Django 4.2.1 on 2023-08-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_qrcodeauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeauth',
            name='token',
        ),
        migrations.AddField(
            model_name='qrcodeauth',
            name='link_with_token',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
