# Generated by Django 4.2.1 on 2023-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_qrcodeauth_token_qrcodeauth_link_with_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodeauth',
            old_name='link_with_token',
            new_name='token',
        ),
        migrations.AddField(
            model_name='qrcodeauth',
            name='url',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
