# Generated by Django 4.2.1 on 2023-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rename_link_with_token_qrcodeauth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeauth',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
