# Generated by Django 4.2.1 on 2023-08-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_qrcodeauth_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeauth',
            name='url',
        ),
    ]
