# Generated by Django 4.2.1 on 2023-08-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('dashboard', '0020_message_read_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='args',
            field=models.JSONField(default={}, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='device',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
    ]
