# Generated by Django 4.2.1 on 2023-08-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0021_alter_log_args_alter_log_device_alter_log_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='rel',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='args',
            field=models.JSONField(null=True),
        ),
    ]
