# Generated by Django 4.2.1 on 2023-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='rel2',
            field=models.ManyToManyField(to='dashboard.configuration'),
        ),
    ]
