# Generated by Django 4.2.1 on 2023-10-27 14:15

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_testmodel_rel2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmodel',
            old_name='rel2',
            new_name='manyToManyRel',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='rel',
            new_name='oneToOneRel',
        ),
        migrations.RenameField(
            model_name='testmodel',
            old_name='is_some',
            new_name='someBool',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='other',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='fileField',
            field=models.FileField(default=None, null=True, upload_to='Media/dashboard/test_model'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='timeField',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.account_image_path),
        ),
    ]
