# Generated by Django 4.2.1 on 2023-10-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_rename_rel2_testmodel_manytomanyrel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
